import Aside from '@/components/Aside/Aside'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='layoutBox'>
          <Aside />
          {children}
        </div>
      </body>
    </html>
  )
}
