import type { Metadata } from 'next';
import RootTemplate from './template';
import Providers from '@/redux/provider';
import { store } from '@/redux/store';
import 'react-toastify/dist/ReactToastify.css'
import '@/scss/style.scss';
import ToastProvider from './ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <ToastProvider>
          <Providers store={store}>
            <RootTemplate>
              {children}
            </RootTemplate>
          </Providers>
        </ToastProvider>
      </body>
    </html>
  )
}
